name: Deploy to Kubernetes
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      UDP_PORT: ${{ vars.UDP_PORT }}
      TCP_HOST: ${{ vars.TCP_HOST }}
      TCP_PORT: ${{ vars.TCP_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deployment manifest
        run: |
          cat <<EOF > deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: siscom-proxy
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: siscom-proxy
            template:
              metadata:
                labels:
                  app: siscom-proxy
              spec:
                containers:
                  - name: siscom-proxy
                    image: ghcr.io/tu-org/siscom-proxy:latest
                    ports:
                      - containerPort: ${UDP_PORT}
                        protocol: UDP
                    env:
                      - name: UDP_PORT
                        value: "${UDP_PORT}"
                      - name: TCP_HOST
                        value: "${TCP_HOST}"
                      - name: TCP_PORT
                        value: "${TCP_PORT}"
                      - name: RUST_LOG
                        value: "info"
          EOF

      - name: Apply to Kubernetes
        run: kubectl apply -f deployment.yaml